#! /bin/sh

### BEGIN INIT INFO
# Provides:		pacCoinTelegramTipBot
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description:	pacCoinTelegramTipBot server
### END INIT INFO

set -e

# /etc/init.d/pacCoinTelegramTipBot: start and stop the pacCoinTelegramTipBot daemon

test -x /opt/pacCoinTipBot/pacCoinTelegramTipBot.py || exit 0

umask 022

. /lib/lsb/init-functions

if [ -n "$2" ]; then
    BOT_OPTS="$BOT_OPTS $2"
fi

# Are we running from init?
run_by_init() {
    ([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
}

check_for_upstart() {
    if init_is_upstart; then
	exit $1
    fi
}

check_dev_null() {
    if [ ! -c /dev/null ]; then
	if [ "$1" = log_end_msg ]; then
	    log_end_msg 1 || true
	fi
	if ! run_by_init; then
	    log_action_msg "/dev/null is not a character device!" || true
	fi
	exit 1
    fi
}

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
	check_for_upstart 1
	check_dev_null
	log_daemon_msg "Starting pacCoinTelegramTipBot server" "PacCoin" || true
	if start-stop-daemon --start --background --quiet --oknodo -u root -p root -m --pidfile /var/run/pacCoinTelegramTipBot.pid --exec /usr/bin/python3 /opt/pacCoinTipBot/pacCoinTelegramTipBot.py -- $BOT_OPTS; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;
  stop)
	check_for_upstart 0
	log_daemon_msg "Stopping pacCoinTelegramTipBot server" "PacCoin" || true
	if start-stop-daemon --stop --quiet --retry 30 --pidfile /var/run/pacCoinTelegramTipBot.pid; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  restart)
	check_for_upstart 1
	log_daemon_msg "Restarting pacCoinTelegramTipBot server" "PacCoin" || true
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile /var/run/pacCoinTelegramTipBot.pid
	check_dev_null log_end_msg
	if start-stop-daemon --start --background --quiet --oknodo -u root -p root -m --pidfile /var/run/pacCoinTelegramTipBot.pid --exec /usr/bin/python3 /opt/pacCoinTipBot/pacCoinTelegramTipBot.py -- $BOT_OPTS; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  status)
	check_for_upstart 1
	status_of_proc -p /var/run/pacCoinTelegramTipBot.pid /opt/pacCoinTipBot/pacCoinTelegramTipBot.py pacCoinTelegramTipBot && exit 0 || exit $?
	;;

  *)
	log_action_msg "Usage: /etc/init.d/pacCoinTelegramTipBot {start|stop|restart|status}" || true
	exit 1
esac

exit 0
